name: Generate Release ðŸš€

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    name: Create Release ðŸš€
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo ðŸ“¥
        uses: actions/checkout@v3

      - name: Set up Node ðŸ› 
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies ðŸ“¦
        run: yarn

      - name: Semantic Release ðŸ”¥
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/npm@9.0.1
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/github@8.0.4
            semantic-release-tags@2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
